language: python
dist: bionic
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.7
        - python: 3.8

# install python dependencies including this package in the travis
# virtualenv
install:
  - ./provision/python.sh

script:
    - pycodestyle mediawiki/
    - coverage run --source=mediawiki setup.py test
    - ./scripts/py-lint.sh

# commands to run after the tests successfully complete
after_success:
  - coveralls
